import { db } from "@workspace/db";
import {
  academyActivitiesTable,
  academyActivityEventsTable,
  academyCoursesTable,
  academyLessonsTable,
  academyModulesTable,
} from "@workspace/db";

const course = {
  id: "course-modelagem-3d",
  slug: "modelagem-3d",
  title: "Modelagem 3D e Preparação para Impressão",
  description:
    "Aprenda do zero ao avançado a criar, otimizar e preparar seus modelos 3D com qualidade profissional.",
  category: "Design & 3D",
  level: "Iniciante ao Avançado",
  duration: "4h 32min",
  modules: 5,
  lessons: 12,
  progress: 50,
  thumbnail: "/course-3d.svg",
  status: "in_progress",
  currentModule: "Modelagem Básica",
  currentLesson: "Criando formas e editando malhas",
  instructor: "Gustavo Simplício",
  instructorRole: "Arquiteto de software e educador",
  objectives: [
    "Criar modelos 3D precisos do zero",
    "Otimizar geometrias e aplicar modificadores",
    "Preparar arquivos para impressão",
    "Organizar um projeto final profissional",
  ],
  requirements: ["Computador com Blender instalado", "Vontade de praticar"],
};

const modules = [
  {
    id: "module-introducao",
    courseId: course.id,
    title: "Introdução",
    description: "Primeiros passos no ambiente 3D.",
    position: 1,
    lessonCount: 2,
    completedLessons: 2,
    progress: 100,
    status: "completed",
  },
  {
    id: "module-modelagem",
    courseId: course.id,
    title: "Modelagem Básica",
    description: "Conceitos e ferramentas essenciais para criar formas.",
    position: 2,
    lessonCount: 5,
    completedLessons: 3,
    progress: 60,
    status: "in_progress",
  },
  {
    id: "module-texturizacao",
    courseId: course.id,
    title: "Texturização e Materiais",
    description: "Dê acabamento e realismo às suas peças.",
    position: 3,
    lessonCount: 3,
    completedLessons: 0,
    progress: 0,
    status: "locked",
  },
  {
    id: "module-preparacao",
    courseId: course.id,
    title: "Preparação para Impressão",
    description: "Valide e exporte seus arquivos.",
    position: 4,
    lessonCount: 1,
    completedLessons: 0,
    progress: 0,
    status: "locked",
  },
  {
    id: "module-final",
    courseId: course.id,
    title: "Projeto Final",
    description: "Coloque tudo em prática.",
    position: 5,
    lessonCount: 1,
    completedLessons: 0,
    progress: 0,
    status: "locked",
  },
];

const lessons = [
  {
    id: "lesson-intro-1",
    courseId: course.id,
    moduleId: "module-introducao",
    title: "Boas-vindas e visão geral",
    duration: "08:15",
    position: 1,
    type: "video",
    status: "completed",
    completed: 1,
    videoPosition: 495,
    videoDuration: 495,
    description: "Conheça o ambiente, a trilha e o projeto que vamos construir.",
    highlights: ["Visão geral do curso", "Como acompanhar o progresso"],
    materials: [],
    nextLessonId: "lesson-intro-2",
  },
  {
    id: "lesson-intro-2",
    courseId: course.id,
    moduleId: "module-introducao",
    title: "Configurando o ambiente",
    duration: "12:40",
    position: 2,
    type: "video",
    status: "completed",
    completed: 1,
    videoPosition: 760,
    videoDuration: 760,
    description: "Deixe o Blender pronto para acompanhar as próximas aulas.",
    highlights: ["Preferências essenciais", "Atalhos recomendados"],
    materials: [
      { id: "material-checklist", name: "Checklist do ambiente", type: "PDF", size: "1.2 MB", url: null },
    ],
    nextLessonId: "lesson-model-1",
  },
  {
    id: "lesson-model-1",
    courseId: course.id,
    moduleId: "module-modelagem",
    title: "Conceitos e ferramentas essenciais",
    duration: "12:43",
    position: 1,
    type: "video",
    status: "completed",
    completed: 1,
    videoPosition: 763,
    videoDuration: 763,
    description: "Entenda a lógica da modelagem e domine as ferramentas mais usadas.",
    highlights: ["Navegação no viewport", "Transformações básicas", "Organização do projeto"],
    materials: [
      { id: "material-hotkeys", name: "Atalhos essenciais", type: "PDF", size: "2.4 MB", url: null },
    ],
    nextLessonId: "lesson-model-2",
  },
  {
    id: "lesson-model-2",
    courseId: course.id,
    moduleId: "module-modelagem",
    title: "Criando formas e editando malhas",
    duration: "18:36",
    position: 2,
    type: "video",
    status: "in_progress",
    completed: 0,
    videoPosition: 522,
    videoDuration: 1116,
    description: "Crie formas com precisão e edite malhas com mais controle.",
    highlights: ["Adicionar e remover faces", "Usar modificadores", "Editar vértices, arestas e faces", "Dicas de otimização de malha"],
    materials: [
      { id: "material-exercise", name: "Exercício da aula", type: "ZIP", size: "8.6 MB", url: null },
      { id: "material-reference", name: "Referência do projeto", type: "STL", size: "3.1 MB", url: null },
    ],
    nextLessonId: "lesson-model-3",
  },
  {
    id: "lesson-model-3",
    courseId: course.id,
    moduleId: "module-modelagem",
    title: "Modelagem de peças complexas",
    duration: "21:10",
    position: 3,
    type: "video",
    status: "locked",
    completed: 0,
    videoPosition: 0,
    videoDuration: 1270,
    description: "Aplique técnicas de precisão em geometrias mais complexas.",
    highlights: ["Booleans", "Topologia limpa"],
    materials: [],
    nextLessonId: "lesson-model-4",
  },
  {
    id: "lesson-model-4",
    courseId: course.id,
    moduleId: "module-modelagem",
    title: "Aplicando modificadores",
    duration: "16:24",
    position: 4,
    type: "video",
    status: "locked",
    completed: 0,
    videoPosition: 0,
    videoDuration: 984,
    description: "Ganhe velocidade e consistência com modificadores.",
    highlights: ["Bevel", "Solidify", "Subdivision"],
    materials: [],
    nextLessonId: "lesson-model-5",
  },
  {
    id: "lesson-model-5",
    courseId: course.id,
    moduleId: "module-modelagem",
    title: "Revisão e prática",
    duration: "24:08",
    position: 5,
    type: "video",
    status: "locked",
    completed: 0,
    videoPosition: 0,
    videoDuration: 1448,
    description: "Revise os conceitos e finalize o exercício do módulo.",
    highlights: ["Checklist de qualidade"],
    materials: [],
    nextLessonId: "lesson-texture-1",
  },
];

const activityEvents = [
  { id: "event-lesson", title: "Aula concluída", course: "Modelagem 3D", time: "Hoje", type: "lesson" },
  { id: "event-quiz", title: "Quiz concluído", course: "Modelagem 3D", time: "Ontem", type: "quiz" },
  { id: "event-module", title: "Módulo concluído", course: "Modelagem 3D", time: "2 dias atrás", type: "module" },
];

const activities = [
  { id: "activity-model", title: "Criar um modelo 3D seguindo as especificações", course: "Modelagem 3D", module: "Modelagem Básica", status: "Pendente", dueDate: "30 set", type: "project" },
  { id: "activity-environment", title: "Checklist do ambiente de trabalho", course: "Modelagem 3D", module: "Introdução", status: "Aprovada", dueDate: "Concluída", type: "practical" },
];

export async function seedAcademy(): Promise<void> {
  await db.insert(academyCoursesTable).values(course).onConflictDoNothing();
  await db.insert(academyModulesTable).values(modules).onConflictDoNothing();
  await db.insert(academyLessonsTable).values(lessons).onConflictDoNothing();
  await db.insert(academyActivityEventsTable).values(activityEvents).onConflictDoNothing();
  await db.insert(academyActivitiesTable).values(activities).onConflictDoNothing();
}